services:
  # Backend API Service
  - type: web
    name: mern-shopping-list-api
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true