services:
  # Backend API Service
  - type: web
    name: mern-shopping-list
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true